
[main]
font=JetBrainsMono Nerd Font:size=13
prompt=""
placeholder="Apps"
width=30
lines=12
horizontal-pad=20
vertical-pad=16
inner-pad=12
line-height=24
icons-enabled=yes
layer=overlay
anchor=center
enable-mouse = yes

[colors]
# RRGGBBAA
background=0b0b0bff
text=cfcfcfff
prompt=cfcfcfff
placeholder=5a5a5aff
input=cfcfcfff
match=f87171ff
selection=00000000
selection-text=fca5a5ff
selection-match=f87171ff
counter=5a5a5aff
border=f87171ff

[border]
width=2
radius=0

