general {
    hide_cursor = true
    disable_loading_bar = true
}

animations {
    enabled = false
}

background {
    monitor =
    color = rgb(000000)
}

label {
    monitor =
    text = $TIME
    color = rgb(F4F4F5)
    font_size = 120
    font_family = JetBrainsMono Nerd Font
    halign = center
    valign = center
    position = 0, 80
}

input-field {
    monitor =
    size = 300, 60
    position = 0, -80
    halign = center
    valign = center

    outline_thickness = 0
    inner_color = rgba(00000000)
    outer_color = rgba(00000000)
    font_color = rgb(F4F4F5)

    dots_size = 0.25
    dots_spacing = 0.35
    dots_center = true
    dots_rounding = -1

    fade_on_empty = false
    rounding = 0
}
