-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:BOE 0x0A11",
  mode = "1920x1080@144.00",
  position = "640x0",
  scale = 1,
  vrr = 0,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:HAT Kamvas 16 0x01010101",
  mode = "1920x1080@59.93",
  position = "-1280x0",
  scale = 1,
  vrr = 0,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})
