# ~/.config/foot/foot.ini

[main]
font=JetBrainsMono Nerd Font:size=16
pad=8x8
term=xterm-256color
initial-window-size-pixels=1000x650

[colors-dark]
foreground=e6e6e6
background=000000

regular0=111111
regular1=ff5555
regular2=50fa7b
regular3=f1fa8c
regular4=5aa9ff
regular5=bd93f9
regular6=50e3e3
regular7=f8f8f2

bright0=44475a
bright1=ff6e6e
bright2=69ff94
bright3=ffffa5
bright4=7ab8ff
bright5=d6acff
bright6=69ffff
bright7=ffffff

[scrollback]
lines=10000

[cursor]
style=block
blink=yes

[mouse]
hide-when-typing=yes
